; Sine of an angle can be computed by making approx sin x ~ x if x is
; sufficiently small, and the trig identity
; sin x = 3 sin(x/3) - 4 sin^3(x/3)
; to reduce the size of the argument of sin. For this excercise, an angle
; is sufficiently small if not greater than 0.1 radians. These ideas are
; incorperated in the following procedures:

(define (cube x) (* x x x))

(define (p x ) (- (* 3 x) (* 4 (cube x))))

(define (sine angle)
    (if (not (> (abs angle) 0.1))
        angle
        (p (sine (/ angle 3.0)))))

; How many times is the procedure p applied when (sine 12.15) is evaluated
(sine 12.15)
(p (sine 4.05))                     1
(p (p (sine 1.35)))                 2
(p (p (p (sine 0.45))))             3
(p (p (p (p (sine 0.15)))))         4
(p (p (p (p (p (sine 0.05))))))     5
(p (p (p (p (p 0.05)))))

p is applied 5 times when (sine 12.15) is evaluated


; What is the order of growth in space and number of steps (as a function
; of a) used by the process generated by the sine procedure when (sine a)
; is evaluated?
(sine a)

Order of growth
O(log a)

Number of Steps
(/ (log (/ a 0.1)) (log 3))